# Generated by Django 3.0.3 on 2020-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('starting_bid', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('current_bid', models.FloatField()),
                ('sold', models.BooleanField()),
                ('bidding', models.BooleanField()),
                ('buyNow', models.BooleanField()),
            ],
        ),
    ]
