# Generated by Django 3.0.3 on 2020-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyNow',
            field=models.FloatField(),
        ),
    ]
