# Generated by Django 3.0.3 on 2020-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatus',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='bidding',
            field=models.BooleanField(default=True),
        ),
    ]
