# Generated by Django 3.0.3 on 2020-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200225_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemstatus',
            old_name='current_bid',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='item',
            name='current_bid',
            field=models.FloatField(null=True),
        ),
    ]
