# Generated by Django 3.0.3 on 2020-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200226_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
