# Generated by Django 3.0.3 on 2020-03-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_item_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buyNow',
        ),
    ]
