# Generated by Django 3.0.3 on 2020-03-19 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_auto_20200318_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='profile',
        ),
        migrations.AddField(
            model_name='item',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
