# Generated by Django 3.0.3 on 2020-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200319_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyNow',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
