# Generated by Django 3.0.3 on 2020-04-03 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200403_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidding_end_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
