# Generated by Django 3.0.3 on 2020-04-03 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200403_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidding_end_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
