# Generated by Django 3.0.3 on 2020-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200403_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('eFurniture', 'eFurniture'), ('Garden Furniture', 'Garden Furniture'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='usedLife',
            field=models.CharField(default='2 Days', max_length=200),
            preserve_default=False,
        ),
    ]
